### 0. Generate auth token
### Запрос на получение токена CSRF для аутентификации
GET http://admin:admin@192.168.0.165:8111/authenticationTest.html?csrf
Accept: application/json

### 1. Create project
### Запрос на создание проекта
POST http://192.168.0.165:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: cebd880a-3ec4-463f-80ca-4904040da680

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name33",
  "id": "id33",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
### Запрос на создание конфигурации сборки
POST http://192.168.0.165:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 2033a61c-ae3f-4fce-b094-5afecd5c8c85

{
  "id": "id_build33",
  "name": "Print hello world",
  "project": {
    "id": "id33"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
### Запрос на запуск сборки
POST http://192.168.0.165:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 5d068440-124f-4756-8b55-9d41c786aed9

{
  "buildType": {
    "id": "id_build33"
  }
}

### 4. Check build status
### Запрос на получение статуса сборки
GET http://192.168.0.165:8111/app/rest/builds/id:202
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 88984ffc-679f-4ac3-baf7-341cd0b4c200


### 5. Turn on permissions
PUT http://192.168.0.165:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: dc786017-3952-4ac1-8942-c31e4c6e66f5

{
  "allowGuest": false,
  "guestUsername": "guest",
  "collapseLoginForm": false,
  "perProjectPermissions": true,
  "emailVerification": false,
  "modules": {
    "module": [
      {
        "name": "Default",
        "properties": {
          "property": [
            {
              "name": "usersCanResetOwnPasswords",
              "value": "true"
            },
            {
              "name": "usersCanChangeOwnPasswords",
              "value": "true"
            },
            {
              "name": "freeRegistrationAllowed",
              "value": "false"
            }
          ],
          "count": 3
        }
      },
      {
        "name": "Token-Auth",
        "properties": {
          "property": [],
          "count": 0
        }
      },
      {
        "name": "HTTP-Basic",
        "properties": {
          "property": [],
          "count": 0
        }
      }
    ]
  }
}

### 6. Verify permissions
#X-TC-CSRF-Token: 74a7cb06-c2b1-4bab-8582-34a95dd52ab0
GET http://192.168.0.165:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: d3a78039-4610-4e85-9484-38f0f06c6c42

### 7. Find projects
GET http://192.168.0.165:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: d3a78039-4610-4e85-9484-38f0f06c6c42

### 8. Find project
GET http://192.168.0.165:8111/app/rest/projects/id%3Atest_nxyRnAuWmp
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 7c2b683d-3224-4b58-88fe-43d3f85f74a0

### 9. Delete project
DELETE  http://192.168.0.165:8111/app/rest/projects/id%3ATestJApUNYeQxh
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: bb40ae60-c961-4ce8-bec0-4a12b3acb06d

### 10. Find builds
GET http://192.168.0.165:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: d7a83cbd-c5cb-43b2-b35b-c4cc31520e57

### 11. Find build
GET http://192.168.0.165:8111/app/rest/buildTypes/id%3ATestiXBIbUXnsw_TestDXJAJTZYzR
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 48b791b0-71c4-44fb-8b31-2e5b4d685d5b

### 12. Put agent
PUT http://192.168.0.165:8111/app/rest/agents/ip_172.17.0.1/authorized
Content-Type: text/plain
Accept: text/plain
X-TC-CSRF-Token: 2307798a-4faa-4fef-a3dc-2162b37d5d13

true

### 13. Get agents /app/rest/agents
GET http://%3A1630286690547818307@192.168.0.165:8111/app/rest/agents
Content-Type: application/json
Accept: application/json
