### 0. Generate auth token
GET http://admin:admin@192.168.0.165:8111/authenticationTest.html?csrf
Accept: application/json

### 1. Create project
POST http://192.168.0.165:8111/app/rest/projects
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 067fbd8e-2f5d-4c6c-a908-653aa2569e08

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "name3",
  "id": "id3",
  "copyAllAssociatedSettings": true
}

### 2. Create build configuration
POST http://192.168.0.165:8111/app/rest/buildTypes
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 8e5d8d7d-534f-4bc6-853a-3f8d7bc56b31

{
  "id": "id",
  "name": "Print hello world",
  "project": {
    "id": "id"
  },
  "steps": {
    "step": [
      {
        "name": "Print hello world",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            },
            {
              "name": "teamcity.step.mode",
              "value": "default"
            },
            {
              "name": "use.custom.script",
              "value": "true"
            }
          ]
        }
      }
    ]
  }
}

### 3. Run build
POST http://192.168.0.165:8111/app/rest/buildQueue
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: b9b860fc-686f-43d6-aa4a-702a5e5b9ac6

{
  "buildType": {
    "id": "id"
  }
}

### 4. Check build status
GET http://192.168.0.165:8111/app/rest/builds/id:103
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 3cee320b-9042-4062-ac6a-e742ba312c8a


### 5. Turn on permissions
PUT http://192.168.0.165:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: dc786017-3952-4ac1-8942-c31e4c6e66f5

{
  "allowGuest": false,
  "guestUsername": "guest",
  "collapseLoginForm": false,
  "perProjectPermissions": true,
  "emailVerification": false,
  "modules": {
    "module": [
      {
        "name": "Default",
        "properties": {
          "property": [
            {
              "name": "usersCanResetOwnPasswords",
              "value": "true"
            },
            {
              "name": "usersCanChangeOwnPasswords",
              "value": "true"
            },
            {
              "name": "freeRegistrationAllowed",
              "value": "false"
            }
          ],
          "count": 3
        }
      },
      {
        "name": "Token-Auth",
        "properties": {
          "property": [],
          "count": 0
        }
      },
      {
        "name": "HTTP-Basic",
        "properties": {
          "property": [],
          "count": 0
        }
      }
    ]
  }
}

### 6. Verify permissions
GET http://192.168.0.165:8111/app/rest/server/authSettings
Content-Type: application/json
Accept: application/json
X-TC-CSRF-Token: 74a7cb06-c2b1-4bab-8582-34a95dd52ab0